In [28]:
import cv2
from matplotlib import pyplot as plt
import numpy as np

obstacleImage = cv2.imread("map.png")
obstacleImage = cv2.cvtColor(obstacleImage, cv2.COLOR_BGR2GRAY)
grid = cv2.threshold(
    obstacleImage, 127, 255, cv2.THRESH_BINARY_INV)[1]
grid = grid/(grid.max()/1.0)
print(grid)

grid[15][3] = 2
grid[24][17] = 2
grid[30][11] = 2
grid[12][11] = 3
grid[2][11] = 3
grid[20][11] = 4
grid[25][12] = 4

gridsize = (32, 32)

def toImage(self, window_size):
        img = np.zeros((gridsize[0], gridsize[1], 3))
        for x in range(gridsize[0]):
            for y in range(gridsize[1]):
                match grid[x][y]:
                    case 0:
                        img[x][y][0] = 255
                        img[x][y][1] = 255
                        img[x][y][2] = 255
                    case 1:
                        img[x][y][0] = 0
                        img[x][y][1] = 0
                        img[x][y][2] = 0
                    case 2:
                        img[x][y][0] = 0
                        img[x][y][1] = 255
                        img[x][y][2] = 0
                    case 3:
                        img[x][y][0] = 255
                        img[x][y][1] = 120
                        img[x][y][2] = 0
                    case 4:
                        img[x][y][0] = 0
                        img[x][y][1] = 0
                        img[x][y][2] = 255
        return cv2.resize(img, window_size, interpolation=cv2.INTER_NEAREST)

newMap = toImage(grid, (400, 400))
cv2.imshow("map", newMap)
  
# waits for user to press any key
# (this is necessary to avoid Python kernel form crashing)
cv2.waitKey(0)
  
# closing all open windows
cv2.destroyAllWindows()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
